# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 600)
        MainWindow.setStyleSheet(".QLabel{ \n"
"         background-color: rgb(255,255,255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setStyleSheet(".QLabel{ \n"
"         background-color: rgb(255,255,255)\n"
"}")
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.gridLayout.addWidget(self.camera_label, 0, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 3)
        self.log_in = QtWidgets.QPushButton(self.centralwidget)
        self.log_in.setObjectName("log_in")
        self.gridLayout.addWidget(self.log_in, 2, 0, 1, 3)
        self.log_out = QtWidgets.QPushButton(self.centralwidget)
        self.log_out.setObjectName("log_out")
        self.gridLayout.addWidget(self.log_out, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "注册"))
        self.log_in.setText(_translate("MainWindow", "登录"))
        self.log_out.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
