# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 601)
        MainWindow.setStyleSheet(".QLabel{ \n"
"         background-color: rgb(255,255,255)\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setMinimumSize(QtCore.QSize(550, 0))
        self.camera_label.setMaximumSize(QtCore.QSize(800, 400))
        self.camera_label.setStyleSheet(".QLabel{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(121, 226, 152, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"")
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.gridLayout.addWidget(self.camera_label, 0, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.log_in = QtWidgets.QPushButton(self.centralwidget)
        self.log_in.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:30px;\n"
"    border-radius:15px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:20px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"     }")
        self.log_in.setObjectName("log_in")
        self.gridLayout.addWidget(self.log_in, 1, 1, 1, 1)
        self.log_out = QtWidgets.QPushButton(self.centralwidget)
        self.log_out.setStyleSheet("QPushButton{\n"
"    border:0px;\n"
"    height:30px;\n"
"    border-radius:15px;\n"
"    font-family:\'Microsoft YaHei\';\n"
"    font-size:20px;\n"
"    color:white;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fbc2eb, stop:1 #a6c1ee);\n"
"    }\n"
"\n"
" QPushButton:hover{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffd2f0, stop:1 #b0cbf8);\n"
" }\n"
" \n"
" QPushButton:pressed{\n"
"     background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e1aad2, stop:1 #92adda);\n"
"     }")
        self.log_out.setObjectName("log_out")
        self.gridLayout.addWidget(self.log_out, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.log_in.setText(_translate("MainWindow", "登录"))
        self.log_out.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
